# Generated by ChatGPT - add other_links to Profile
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_job_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_links',
            field=models.TextField(default='{}'),
        ),
    ]
