# Generated by ChatGPT - add application_link to Job
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_add_other_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
