# Generated by ChatGPT - add resume fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_add_application_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='resumes/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='application_resumes/', null=True, blank=True),
        ),
    ]
