# Generated by ChatGPT - add application status fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_add_resume_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
